print('Electricity bill details: ')
consumer_name = input('Enter Consumer Name: ')
consumer_no = int(input('Enter Consumer Number: '))
service_address = input("Enter consumer address: ")
meter_number  = str(input("Enter meter number: "))
bill_no = str(input("Enter bill number: "))
fromdate = input("Enter From Date: ")
todate = input("To Date: ")
bill_date = input("enter bill  date: ")
due_date = input('Enter due date: ')
previous_reading = int(input("Previous Reading: "))
cur_reading = int(input('Current reading: '))
units = int(input("Units consumed: "))
Energychrgs = int(input("Energy charges: "))
Fixedchrgs = int(input("Fixed charges: "))
Taxchrgs = int(input("Tax charges: "))
total = Energychrgs + Fixedchrgs + Taxchrgs
payment_status = bool(input("Enter T or F"))


print('\n\n------------------------------------------------')
print('--------------- ELECTRICITY BILL -------------------')
print('----------------------------------------------------')
print('Consumer Name: ',consumer_name)
print('Consumer No. : ',consumer_no)
print('Address: ',service_address)
print('Meter No. : ',meter_number)
print('\nBill No. : ',bill_no)
print('Billing Period: ',fromdate,'to',todate)
print('Bill Date: ',bill_date)
print('Due Date: ',due_date)
print('\nPrevious Reading: ',previous_reading,'kWh')
print('Current Reading: ',cur_reading,'kWh')
print("Units Consumed: ",units,'kWh')
print('\nEnergy Charges: ₹',float(Energychrgs))
print('Fixed Charges: ₹',float(Fixedchrgs))
print('Taxes & Fees: ₹',float(Taxchrgs))
print('\n\n-------------------------')
print('TOTAL AMOUNT: ₹',float(total))
print('---------------------------')
print('\n\n Payment Status: ',end = '')
if( payment_status == True): print('Paid')
else:print("Unpaid")
print('------------------------------------------------------')
